version: 3.7
services:
  php:
    image: manchenkoff/php-xdebug
    container_name: app
    ports:
      - 80:80
      - 443:443
    build:
      context: src
    volumes:
      - ./src/app:/var/www/app
    env_file:
      - .env